---
- name: "Configure localhost"
  hosts: "localhost"

  vars:
    ansible_pull_service_url: "https://github.com/dschier-wtd/fedora-iot.git"
    ansible_pull_service_sleep: "30"
    ansible_pull_timer_schedule: "*:0/30:00"

  tasks:

    - name: "Deploy Ansible Pull"
      ansible.builtin.import_tasks:
        file: "tasks/deploy_ansible_pull.yml"

    - name: "Deploy Podman"
      ansible.builtin.import_tasks:
        file: "tasks/deploy_podman.yml"

    - name: "Deploy Web Container"
      ansible.builtin.import_tasks:
        file: "tasks/deploy_web_container.yml"
...
