---
- name: "Install Requirements"
  hosts: "localhost"
  gather_facts: false

  tasks:

    - name: "Install requirements"
      ansible.builtin.command:
        cmd: "ansible-galaxy collection install -r ../collections/requirements.yml"
      tags:
        - "requirements"
...
