---
- name: "Download Image"
  containers.podman.podman_image:
    name: "docker.io/library/mariadb"
    tag: "latest"
    state: "present"
  become: true
  tags:
    - "image"
    - "podman"
    - "web"

- name: "Manage container-mariadb Service File"
  ansible.builtin.template:
    src: "container-mariadb.service.j2"
    dest: "/etc/systemd/system/container-mariadb.service"
    owner: "root"
    group: "root"
    mode: 0644
  become: true

- name: "Manage container-mariadb Service"
  ansible.builtin.systemd:
    name: "container-mariadb.service"
    state: "started"
    enabled: true
    daemon_reload: true
  become: true
...
