---
- name: "Download Image"
  containers.podman.podman_image:
    name: "docker.io/library/nginx"
    tag: "latest"
    state: "present"
  become: true
  tags:
    - "image"
    - "podman"
    - "web"

- name: "Manage Service File"
  ansible.builtin.template:
    src: "container-web.service.j2"
    dest: "/etc/systemd/system/container-web.service"
    owner: "root"
    group: "root"
    mode: 0644
  become: true

- name: "Manage container-web Service"
  ansible.builtin.service:
    name: "container-web.service"
    state: "started"
    enabled: true
  become: true
...
